# Generated by Django 2.2 on 2024-01-17 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administradores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminitrador',
            name='apellido',
            field=models.CharField(default=1, max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_alpha', message='Debe contener solo caracteres alfabéticos y espacios.', regex='^[A-Za-z\\s]+$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminitrador',
            name='nombre',
            field=models.CharField(default=1, max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_alpha', message='Debe contener solo caracteres alfabéticos y espacios.', regex='^[A-Za-z\\s]+$')]),
            preserve_default=False,
        ),
    ]
