# Generated by Django 2.2 on 2024-01-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='confirmar_clave',
            field=models.CharField(default='', max_length=50),
        ),
    ]
