# Generated by Django 2.2 on 2024-01-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='es_admin',
            field=models.BooleanField(default=False),
        ),
    ]
