# Generated by Django 2.2 on 2024-01-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_persona_es_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nombre',
        ),
    ]
