# Generated by Django 2.2 on 2024-01-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20240117_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='clave',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='username',
        ),
    ]
