# Generated by Django 2.2 on 2024-01-08 10:53

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20240108_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='apellido',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_alpha', message='Debe contener solo caracteres alfabéticos y espacios.', regex='^[A-Za-z\\s]+$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='nombre',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_alpha', message='Debe contener solo caracteres alfabéticos y espacios.', regex='^[A-Za-z\\s]+$')]),
            preserve_default=False,
        ),
    ]
