# Generated by Django 4.1.1 on 2024-04-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userrol_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrol',
            name='ultimaConexion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
