# Generated by Django 4.1.1 on 2024-04-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userrol_ultimaconexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrol',
            name='ultimaActividad',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
