# Generated by Django 2.2 on 2024-01-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mutual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cuit', models.CharField(max_length=30)),
                ('estado', models.BooleanField()),
                ('fecha_subida', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
