# Generated by Django 2.2 on 2024-01-05 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaracionJurada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('R', 'reclamo'), ('P', 'prestamo')], max_length=1)),
                ('fecha_subida', models.DateField()),
                ('fecha_rectificacion', models.DateField()),
                ('periodo_declarado', models.DateField()),
                ('mutual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutual.Mutual')),
            ],
        ),
    ]
