# Generated by Django 2.2 on 2024-01-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declaracionjurada',
            old_name='archivo_sub',
            new_name='archivo',
        ),
    ]
