# Generated by Django 2.2 on 2024-01-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0002_auto_20240118_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declaracionjurada',
            old_name='archivo',
            new_name='archivo_sub',
        ),
    ]
