# Generated by Django 2.2 on 2024-01-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0002_auto_20240109_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutual',
            name='cuit',
            field=models.BigIntegerField(),
        ),
    ]
