# Generated by Django 2.2 on 2024-01-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0002_auto_20240129_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declaracionjurada',
            old_name='leida',
            new_name='es_leida',
        ),
        migrations.AddField(
            model_name='declaracionjurada',
            name='es_borrador',
            field=models.BooleanField(default=True),
        ),
    ]
