# Generated by Django 2.2 on 2024-01-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0003_auto_20240131_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracionjurada',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
