# Generated by Django 2.2 on 2024-01-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0003_auto_20240109_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutual',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
