# Generated by Django 2.2 on 2024-01-18 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0004_auto_20240118_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracionjurada',
            name='fecha_subida',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='declaracionjurada',
            name='periodo_mes',
            field=models.CharField(max_length=25),
        ),
    ]
