# Generated by Django 2.2 on 2024-01-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0004_auto_20240110_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracionjurada',
            name='archivo',
            field=models.FileField(default=1, upload_to='documentos/'),
            preserve_default=False,
        ),
    ]
