# Generated by Django 2.2 on 2024-01-31 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0004_auto_20240131_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracionjurada',
            name='periodo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mutual.Periodo'),
            preserve_default=False,
        ),
    ]
