# Generated by Django 2.2 on 2024-01-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0005_auto_20240118_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaracionjurada',
            name='archivo',
        ),
        migrations.AddField(
            model_name='declaracionjurada',
            name='archivos',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
