# Generated by Django 2.2 on 2024-02-01 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0005_declaracionjurada_periodo'),
        ('mutual', '0004_declaracionjurada_fecha_creacion'),
    ]

    operations = [
    ]
