# Generated by Django 2.2 on 2024-01-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0006_auto_20240119_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declaracionjurada',
            old_name='periodo_mes',
            new_name='periodo',
        ),
    ]
