# Generated by Django 2.2 on 2024-02-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0006_merge_20240201_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='fecha_fin',
            field=models.DateField(blank=True),
        ),
    ]
