# Generated by Django 2.2 on 2024-01-19 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0007_auto_20240119_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutual',
            name='cuit',
            field=models.CharField(max_length=11, validators=[django.core.validators.MaxValueValidator(99999999999)]),
        ),
    ]
