# Generated by Django 2.2 on 2024-02-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0008_auto_20240201_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracionjurada',
            name='fecha_subida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
