# Generated by Django 2.2 on 2024-01-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0008_auto_20240119_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracionjurada',
            name='archivos',
            field=models.FileField(upload_to='documentos/'),
        ),
    ]
