# Generated by Django 2.2 on 2024-01-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0009_auto_20240122_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracionjurada',
            name='leida',
            field=models.BooleanField(default=False),
        ),
    ]
