# Generated by Django 2.2 on 2024-02-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0009_auto_20240208_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledeclaracionjurada',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
