# Generated by Django 2.2 on 2024-01-25 11:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0010_declaracionjurada_leida'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracionjurada',
            name='codigo_acuse_recibo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='declaracionjurada',
            name='rectificativa',
            field=models.IntegerField(default=0),
        ),
    ]
