# Generated by Django 2.2 on 2024-02-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0010_auto_20240215_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracionjurada',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='declaracionjurada',
            name='fecha_subida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
