# Generated by Django 2.2 on 2024-01-26 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0011_auto_20240125_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaracionjurada',
            name='archivos',
        ),
        migrations.RemoveField(
            model_name='declaracionjurada',
            name='leida',
        ),
        migrations.RemoveField(
            model_name='declaracionjurada',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='declaracionjurada',
            name='periodo',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='DetalleDeclaracionJurada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_concepto', models.CharField(choices=[('P', 'prestamo'), ('R', 'reclamo')], max_length=1)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('leida', models.BooleanField(default=False)),
                ('total_registros', models.IntegerField(default=0)),
                ('declaracion_jurada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutual.DeclaracionJurada')),
            ],
        ),
    ]
