# Generated by Django 2.2 on 2024-02-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0011_auto_20240221_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallemutual',
            name='concepto_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallemutual',
            name='concepto_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
