# Generated by Django 2.2 on 2024-02-29 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0012_auto_20240228_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracionjurada',
            name='fecha_lectura',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
