# Generated by Django 2.2 on 2024-01-26 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0012_auto_20240126_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalledeclaracionjurada',
            old_name='tipo_concepto',
            new_name='tipo',
        ),
    ]
