# Generated by Django 2.2 on 2024-02-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0013_declaracionjurada_fecha_lectura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracionjurada',
            name='fecha_lectura',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
