# Generated by Django 2.2 on 2024-01-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0013_auto_20240126_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalledeclaracionjurada',
            name='leida',
        ),
        migrations.AddField(
            model_name='declaracionjurada',
            name='leida',
            field=models.BooleanField(default=False),
        ),
    ]
