# Generated by Django 4.1.1 on 2024-03-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0015_alter_declaracionjurada_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutual',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
    ]
