# Generated by Django 4.1.1 on 2024-03-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0016_alter_mutual_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutual',
            name='alias',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mutual',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
