# Generated by Django 4.1.1 on 2024-03-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0018_alter_mutual_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutual',
            name='cuit',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
