# Generated by Django 4.1.1 on 2024-04-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0019_alter_mutual_cuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledeclaracionjurada',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True),
        ),
    ]
