# Generated by Django 4.1.1 on 2024-04-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0020_alter_detalledeclaracionjurada_importe'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalledeclaracionjurada',
            name='es_concepto1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detalledeclaracionjurada',
            name='es_concepto2',
            field=models.BooleanField(default=False),
        ),
    ]
