# Generated by Django 4.1.1 on 2024-04-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0021_detalledeclaracionjurada_es_concepto1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalledeclaracionjurada',
            name='es_concepto1',
        ),
        migrations.RemoveField(
            model_name='detalledeclaracionjurada',
            name='es_concepto2',
        ),
        migrations.AddField(
            model_name='detalledeclaracionjurada',
            name='concepto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
