# Generated by Django 4.1.1 on 2024-04-22 11:00

import apps.mutual.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0022_remove_detalledeclaracionjurada_es_concepto1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledeclaracionjurada',
            name='archivo',
            field=models.FileField(upload_to=apps.mutual.models.archivo_path),
        ),
    ]
