# Generated by Django 2.2 on 2024-01-29 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0004_auto_20240118_1238'),
        ('mutual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Rol')),
                ('mutual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutual.Mutual')),
            ],
            bases=('personas.rol',),
        ),
    ]
