# Generated by Django 2.2 on 2024-01-17 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mutual', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='mutual',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mutual.Mutual'),
            preserve_default=False,
        ),
    ]
