# Usa una imagen base de Python
FROM python:3.10

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia el archivo requirements.txt a la imagen
COPY ./requirements.txt .

# Instala las dependencias de Django desde el requirements.txt
RUN pip install -r requirements.txt

# Copia los archivos de tu proyecto al contenedor
COPY . .

# Expone el puerto en el que tu aplicación Django escucha (opcional, depende de cómo configures Django)
EXPOSE 8000

# Comando para iniciar tu aplicación Django cuando se ejecute el contenedor
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]


